development:
  cloud_name: chefsocial
  api_key: <%= ENV['COUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: chefsocial
  api_key: <%= ENV['COUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: chefsocial
  api_key: <%= ENV['COUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
