# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d65633abef9a964fb59b060785d9ab6add4e432e798a90d929f82a18ab718b9adbbeffdfacf8450d49c4e13038e50f57d4bdd07efe3ce94c6f091213940fb7c5

test:
  secret_key_base: af52df2e62a57abd79c90e50f170f2b23dddc4e83b91ad54cbff20ef4b94a6aa8587e0e9dfee9955054457aab64875098fbc7ce40b8d909a50931cdade77f1b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
